spring.application.name=bioswork
server.port = 8081

spring.web.locale=es_UY
spring.web.locale-resolver=fixed
 
server.tomcat.max-swallow-size=-1
 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/tmp
spring.servlet.multipart.max-file-size=2MB
 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bios_work?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
# spring.datasource.username=${ubd}
# spring.datasource.password=${cbd}
# En producción no utilizaremos el usuario root, sino que crearemos un usuario para la aplicación en la BD,
# que disponga únicamente de los permisos mínimos que necesita ésta para funcionar correctamente.
 
spring.sql.init.encoding=UTF-8
spring.sql.init.separator=^;
spring.sql.init.mode=always
 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true